apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded administrative credentials:
  # username: mongo-admin (bW9uZ28tYWRtaW4=)
  # password: db-secret-password-123 (ZGItc2VjcmV0LXBhc3N3b3JkLTEyMw==)
  MONGO_INITDB_ROOT_USERNAME: bW9uZ28tYWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: ZGItc2VjcmV0LXBhc3N3b3JkLTEyMw==
